steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - REACT_APP_STORE_API_URL=${_REACT_APP_STORE_API_URL}
      - --build-arg
      - REACT_APP_STORE_BASE_URL=${_REACT_APP_STORE_BASE_URL}
      - --build-arg
      - REACT_APP_API_SERVER_BASE_URL=${_REACT_APP_API_SERVER_BASE_URL}
      - '-t'
      - >-
        ${_REPO_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA
      - '-f'
      - admin-front/Dockerfile
      - .
    id: Build Image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        ${_REPO_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA
    id: Push Image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - deploy
      - '${_SERVICE_NAME}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=${_MIN_INSTANCE}'
      - '--max-instances=${_MAX_INSTANCE}'
      - '--cpu=${_CPU}'
      - '--memory=${_MEMORY}'
      - '--service-account=${_SERVICE_ACCOUNT}'
      - >-
        --image=${_REPO_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID
      - >-
        --set-env-vars=REACT_APP_STORE_API_URL=${_REACT_APP_STORE_API_URL},REACT_APP_STORE_BASE_URL=${_REACT_APP_STORE_BASE_URL},REACT_APP_API_SERVER_BASE_URL=${_REACT_APP_API_SERVER_BASE_URL}
      - '--region=${_DEPLOY_REGION}'
      - '--quiet'
      - '--port=${_PORT}'
    id: Deploy to Cloud Run
    entrypoint: gcloud
options:
  machineType: E2_HIGHCPU_32
  dynamicSubstitutions: true
substitutions:
  _MEMORY: 1Gi
  _REPOSITORY: tznftwebshop
  _SERVICE_ACCOUNT: cloud-run-sa@concordia-development.iam.gserviceaccount.com
  _PORT: '80'
  _REPO_REGION: europe-west2
  _MAX_INSTANCE: '4'
  _MIN_INSTANCE: '1'
  _CPU: '1'
  _SERVICE_NAME: frontend-admin
  _DEPLOY_REGION: europe-west2
  _REACT_APP_STORE_API_URL: 'https://phase3-api-lgcyj3d5ja-nw.a.run.app'
  _REACT_APP_STORE_BASE_URL: 'https://frontend-phase-3-lgcyj3d5ja-nw.a.run.app'
  _REACT_APP_API_SERVER_BASE_URL: 'https://admin-api-lgcyj3d5ja-nw.a.run.app'
